### ISSUE TITLE
angular2 rc.3

### ISSUE THREAD

**Issue by TobiasKrogh** [tb/ng2-nouislider#1]
Hi,

the third Release Candidate has been released. The ng2-nouislider unfortunately does not work anymore:

```
ERROR in ./~/ng2-nouislider/src/nouislider.js
Module not found: Error: Cannot resolve module '@angular/common/src/forms/directives/control_value_accessor' in /vagrant/solaris_
frontend/node_modules/ng2-nouislider/src
 @ ./~/ng2-nouislider/src/nouislider.js 13:31-101
```

Maybe you can take a look? :)

Cheers,
Tobi

**Comment by TobiasKrogh** [comment]
EDIT: updated regarding third release candidate (sorry for spam)

**Comment by tb** [comment]
It should work now with angular2 rc3, see commit https://github.com/tb/ng2-nouislider/commit/59263faf88b23e4a605e0f4d8aa0a77256fb48fd

**Comment by TobiasKrogh** [comment]
@tb unfortunately not yet completely. I encountered several small things.

Just updating the package shows the following error which is related to the forms related API changes that happened in Angular 2 RC 2:

```
ORIGINAL EXCEPTION: Name attribute must be set if ngModel is used within a form.
                      Example: <input [(ngModel)]="person.firstName" name="first">
```

This is reported by the template parser. Therefore simply writing `name="my-name"` it in the template seems enough. You might want to extend the documentation for that.

When this works I see another error reported by zone.js

```
EXCEPTION: Error: Uncaught (in promise): No value accessor for 'foobar'
```

Which I think is related to the fact that you are using the "old" value accessor. They should be imported from "@angular/forms" imho. 

```
import {
  ControlValueAccessor,
  NG_VALUE_ACCESSOR
} from '@angular/forms';
```

Can you double check please?

**Comment by tb** [comment]
@TobiasKrogh  Please note I am not using input in any place on demos - nouislider is always on div and has ngModel - see http://tb.github.io/ng2-nouislider/

There are form directives in Material2 repository, thats where I look at as reference for changes, i.e. https://github.com/angular/material2/blob/master/src/components/checkbox/checkbox.ts

You can also build the code locally with:

    git clone git@github.com:tb/ng2-nouislider.git
    cd ng2-nouislider
    npm i
    npm start

**Comment by TobiasKrogh** [comment]
@tb Please note that the `Example: <input [(ngModel)]="person.firstName" name="first">` is just an *example* being given by the template parser when an exception is logged. It expects a name attribute on an element with ngModel if that element is used inside of a form (which might happen for a slider imho). I think it does not check whether this attribute is really necessary it is just the parser.

My markup:
```
<form>
  <div
    #slider
    nouislider
    [connect]="true"
    [min]="0"
    [max]="15"
    [step]="1"
    [(ngModel)]="fields[filter.key]">
  </div>
</form>
```

I will just use the slider apart from all other form controls. Still there remains the issue with the value accessor.

As you can read here: http://angularjs.blogspot.de/2016/06/rc2-now-available.html There were major changes to Forms and as soon as someone uses the disableDeprecatedForms directives have to be imported from @angular/forms instead of @angular/common (API change proposal: https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub)

I have no idea when material2 will follow up but they also seem not to be fully migrated yet (checking their https://github.com/angular/material2/blob/master/CHANGELOG.md).

I found an up 2 date example here: https://github.com/primefaces/primeng/blob/master/components/checkbox/checkbox.ts

---

I also tried to clone the ng2-nouislider repo but ended up with an empty demo folder so I cannot try it myself. Else I would have set up a pull request. Still can do if you give me a hint about how to manage to get the demo running properly. The latests commit in the demo folder also looks related to rc.1

**Comment by tb** [comment]
@TobiasKrogh Ah, to get demo you need `git clone --recursive git@github.com:tb/ng2-nouislider.git`.

I wont be able to look at it till evening.

**Comment by TobiasKrogh** [comment]
@tb thanks... will try to look into it

**Comment by TobiasKrogh** [comment]
created https://github.com/tb/ng2-nouislider/pull/3
