### ISSUE TITLE
using System.js getting error - caused by: noUiSlider.create is not a function

### ISSUE THREAD

**Issue by dalibor-sanzeru** [tb/ng2-nouislider#10]
Hi,
Can this component be used with System.js as well? (Is there any System.js demo?)
Using system.js -> I am getting error **caused by: noUiSlider.create is not a function**

TS -> nouislider.ts -> line  81:
**this.slider = noUiSlider.create(**

create is function of what - html element, webpack..? I am confused from import * from ... in the first line.

Thank you very much for advice.
Dalibor.

**Comment by tb** [comment]
It looks like you are missing node_modules/nouislider.

For Systemjs setup you can check https://github.com/tb/ng2-nouislider/issues/7 Let me know if it worked, I will add it to README.
