### ISSUE TITLE
Can't resolve 'nouislider

### ISSUE THREAD

**Issue by andy5638** [tb/ng2-nouislider#101]
I am using angular 4.3.5 with angular/cli 1.3.1 on Windows 10.
I tried to import ng2-nouislider to my certain module which uses slider, but I didn't import it at app.module.
Then I tried "ng serve" and cli starts building, then the error occurred:

ERROR in ./node_modules/ng2-nouislider/src/nouislider.js
Module not found: Error: Can't resolve 'nouislider' in 'D:\Downloads\Projects\frontend_angular\node_modules\ng2-nouislider\src'
resolve 'nouislider' in 'D:\Downloads\Projects\frontend_angular\node_modules\ng2-nouislider\src'
  Parsed request is a module
  using description file: D:\Downloads\Projects\frontend_angular\node_modules\ng2-nouislider\package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\Downloads\Projects\frontend_angular\node_modules\ng2-nouislider\package.json (relative path: ./src)
    resolve as module
      D:\Downloads\Projects\frontend_angular\node_modules\ng2-nouislider\src\node_modules doesn't exist or is not a directory
      D:\Downloads\Projects\frontend_angular\node_modules\ng2-nouislider\node_modules doesn't exist or is not a directory
      D:\Downloads\Projects\frontend_angular\node_modules\node_modules doesn't exist or is not a directory
      D:\Downloads\Projects\node_modules doesn't exist or is not a directory
      D:\Downloads\node_modules doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
      looking for modules in D:\Downloads\Projects\frontend_angular\node_modules
        using description file: D:\Downloads\Projects\frontend_angular\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\Downloads\Projects\frontend_angular\package.json (relative path: ./node_modules)
          using description file: D:\Downloads\Projects\frontend_angular\package.json (relative path: ./node_modules/nouislider)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\Downloads\Projects\frontend_angular\node_modules\nouislider doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\Downloads\Projects\frontend_angular\node_modules\nouislider.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\Downloads\Projects\frontend_angular\node_modules\nouislider.js doesn't exist
            as directory
              D:\Downloads\Projects\frontend_angular\node_modules\nouislider doesn't exist
      looking for modules in D:\Downloads\Projects\frontend_angular\node_modules
        using description file: D:\Downloads\Projects\frontend_angular\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\Downloads\Projects\frontend_angular\package.json (relative path: ./node_modules)
          using description file: D:\Downloads\Projects\frontend_angular\package.json (relative path: ./node_modules/nouislider)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\Downloads\Projects\frontend_angular\node_modules\nouislider doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\Downloads\Projects\frontend_angular\node_modules\nouislider.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\Downloads\Projects\frontend_angular\node_modules\nouislider.js doesn't exist
            as directory
              D:\Downloads\Projects\frontend_angular\node_modules\nouislider doesn't exist

**Comment by andy5638** [comment]
Somehow this issue disappeared, close this issue.

**Comment by mr-sige** [comment]
I'm having the same issue.
