### ISSUE TITLE
How I can customize my pips label to have string values?

### ISSUE THREAD

**Issue by aishwaryagarg** [tb/ng2-nouislider#107]
I want my ticks labels to have value ["abc","pqr","xyz"] instead of [1,2,3]. I tried using format option but its helpful to format the numeric value. we are not able to entirely format the label into alphabetic string.

**Comment by kiqq** [comment]
I hope this code will help You:

`<nouislider [config]="sliderConfig"></nouislider>`

```
public sliderConfig: any = {
    connect: true,
    start: 3,
    step: 1,
    range: {
      'min': [-3],
      'max': [10]
    },
    pips: {
      mode: 'steps',
      density: 3,
      format: new MyFormatter()
    }
  };
```

```
import { NouiFormatter } from "ng2-nouislider/src/nouislider";

export class MyFormatter implements NouiFormatter {
  private strings: string[] = [
    'abc', 'dfg', 'hij', 'klm', 'nop', 'qrs', 'tuv', 'wxy', 'z'
  ];

  to(value: number): string {
    value = Math.round(value);
    if (value < 0) {
      value = 0;
    }
    if (value >= this.strings.length) {
      value = this.strings.length - 1;
    }
    return this.strings[value];
  }

  from(value: string): number {
    let result = this.strings.indexOf(value);
    return result == -1 ? 0 : result;
  }
}
```

**Comment by duahimanshu100** [comment]
@kiqq How can i add custom images instead of string values. Please help

**Comment by WebmasterRF** [comment]
Cool, I got this work. A better example of this needs to be added to the site, this is an important feature. Thanks.

**Comment by SnisarOnline** [comment]
but this answer valid only static array

**Comment by Moji0098** [comment]
cant get this working with dynamic array .
`import { NouiFormatter } from "ng2-nouislider/src/nouislider";

export class MyFormatter implements NouiFormatter {
    constructor(formaterArray) {
        this.strings =formaterArray;
    }
  private strings: string[];

  to(value: number): string {
    value = Math.round(value);
    if (value < 0) {
      value = 0;
    }
    if (value >= this.strings.length) {
      value = this.strings.length - 1;
    }
    return this.strings[value];
  }

  from(value: string): number {
    let result = this.strings && this.strings.indexOf(value);
    return result == -1 ? 0 : result;
  }
}`

I'm using this function to create dynamic config : 
 
`createSliderConfig (formaterArray , range) {
    return  {
      behaviour: 'tap',
      connect: true,
      start: [1],
      handle : 1,
      step:1,
      keyboard: true,  // same as [keyboard]="true"
      
      pageSteps: 10,  // number of page steps, defaults to 10
      range: {
        min: range[0],
        max: range[1]
      },
      pips: {
        mode: 'count',
        density: 20,
        values: 10,
        stepped:true,
        format:new MyFormatter(formaterArray)
      }
      
    };
  }`
