### ISSUE TITLE
Unexpected directive 'Nouislider' imported by the module 

### ISSUE THREAD

**Issue by bonaparte89** [tb/ng2-nouislider#11]
hello,

I'm using the angular2-seed by mgechev... (systemjs)
I got the slider working, but just if i declare it in the ngmodule... importing throws the error above.
declaring it in two modules throws of course the known error.
i mapped it and added it to packages --> #7 

any suggestions?

thanks

**Comment by neilhem** [comment]
Seems like ng2-nouislider does not support angular 2 modules

**Comment by tb** [comment]
No exports as `NouisliderModule`. Updated readme and released as 1.0.0 🎉 🎉 🎉
