### ISSUE TITLE
Error: Unexpected value 'NouisliderModule in ...

### ISSUE THREAD

**Issue by iCodr8** [tb/ng2-nouislider#116]
When I am building my project for production the following error is appearing.

```
Error: Unexpected value 'NouisliderModule in /path-to-project/node_modules/ng2-nouislider/src/nouislider.js' imported by the module 'MyModule in /path-to-project/src/my.module.ts'. Please add a @NgModule annotation.
```

Has anyone a tip for me? I don't know why this error occurs.

**Comment by iCodr8** [comment]
Version 1.7.0

**Comment by iCodr8** [comment]
I changed
```
import {NouisliderModule} from 'ng2-nouislider';
```
to
```
import {NouisliderModule} from 'ng2-nouislider/src/nouislider';
```
and now it is working... But this is not a nice solution. I think there should be added an `index.ts` that has a reference to the `src/nouislider` directory.

**Comment by kikukiks** [comment]
I'm having the same issue. I've just updated my dependencies as well, so my `ng -v` output looks like this:
```
@angular/cli: 1.4.2                     
node: 7.10.0                            
os: linux x64                           
@angular/animations: 4.4.1              
@angular/common: 4.4.1                  
@angular/compiler: 4.4.1                
@angular/core: 4.4.1                    
@angular/forms: 4.4.1                   
@angular/http: 4.4.1                    
@angular/platform-browser: 4.4.1        
@angular/platform-browser-dynamic: 4.4.1
@angular/router: 4.4.1                  
@angular/cli: 1.4.2                     
@angular/compiler-cli: 4.4.1            
@angular/language-service: 4.4.1        
typescript: 2.3.4
```
I haven't been able to solve this for hours. I'm also having problems when I serve the application using `ng-serve`. It fails the first time, giving me `ERROR in Error: NouisliderModule is not an NgModule`. Although, when I rebuild, it runs beautifully.

Building the project with AOT always fails with this:
```
ERROR in Error: Unexpected value 'NouisliderModule in /path/node_modules/ng2-nouislider/src/nouislider.js' imported by the module 'AppModule in /path/src/app/app.module.ts'. Please add a @NgModule annotation.
```

These are the issues that I've combed through, but to no avail:
https://github.com/angular/angular/issues/15763
https://github.com/angular/angular-cli/issues/3426

**Comment by kikukiks** [comment]
@iCodr8 This workaround is indeed working. Thank you for that! At least I can continue development until there is an actual fix to the issue.

**Comment by TVrijdag** [comment]
I think that adding `"typings": "src/nouislider.d.ts"` to the package.json should fix the issue
