### ISSUE TITLE
multiple nouislider with different behaviors 

### ISSUE THREAD

**Issue by jahmed31** [tb/ng2-nouislider#127]
Hi,

I want to add multiple sliders with different selection on them. But all sliders works together , i want to work them separately. Any suggestions. my code is pasted down. 

> <fieldset>
      <h5>Male/Female Breakdown</h5>
      <div class="col-sm-6">
        <div class="male-female">
          <span class="col-sm-2">%{{male_gender}} Male</span>
          <span>
            <nouislider [min]="someMin" [max]="someLimit" [step]="1.00" [(ngModel)]="male_gender" [tooltips]="[true]" name="male-female"></nouislider>
          </span>
          <span>%{{100 - male_gender}} Female</span>
        </div>
      </div>
    </fieldset>
    <fieldset>
      <h3>Age Breakdown</h3>
      <div class="col-sm-6">
        <div class="male-female">
          <span class="col-sm-2">Under 7</span>
          <span>
            <nouislider [min]="someMin" [max]="someLimit" [step]="1.00" [(ngModel)]="under_7" name="under_7"></nouislider>
          </span>
          <span>%{{under_7}}</span>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="col-sm-6">
        <div class="male-female">
          <span class="col-sm-2">7-11</span>
          <span>
            <nouislider [min]="someMin" [max]="someLimit" [step]="1.00" [(ngModel)]="under_7_11" name="under_7"></nouislider>
          </span>
          <span>%{{under_7_11}}</span>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="col-sm-6">
        <div class="male-female">
          <span class="col-sm-2">12-17</span>
          <span>
            <nouislider [min]="someMin" [max]="someLimit" [step]="1.00" [(ngModel)]="under_12_17" name="under_12_17"></nouislider>
          </span>
          <span>%{{under_12_17}}</span>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="col-sm-6">
        <div class="male-female">
          <span class="col-sm-2">18-24</span>
          <span>
            <nouislider [min]="someMin" [max]="someLimit" [step]="1.00" [(ngModel)]="under_18_24" name="under_18_24"></nouislider>
          </span>
          <span>%{{under_18_24}}</span>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="col-sm-6">
        <div class="male-female">
          <span class="col-sm-2">25-34</span>
          <span>
            <nouislider [min]="someMin" [max]="someLimit" [step]="1.00" [(ngModel)]="under_25_34" name="under_25_34"></nouislider>
          </span>
          <span>%{{under_25_34}}</span>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="col-sm-6">
        <div class="male-female">
          <span class="col-sm-2">35-44</span>
          <span>
            <nouislider [min]="someMin" [max]="someLimit" [step]="1.00" [(ngModel)]="under_35_44" name="under_35_44"></nouislider>
          </span>
          <span>%{{under_35_44}}</span>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="col-sm-6">
        <div class="male-female">
          <span class="col-sm-2">45-54</span>
          <span>
            <nouislider [min]="someMin" [max]="someLimit" [step]="1.00" [(ngModel)]="under_45_54" name="under_45_54"></nouislider>
          </span>
          <span>%{{under_45_54}}</span>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="col-sm-6">
        <div class="male-female">
          <span class="col-sm-2">55-64</span>
          <span>
            <nouislider [min]="someMin" [max]="someLimit" [step]="1.00" [(ngModel)]="under_55_64" name="under_55_64"></nouislider>
          </span>
          <span>%{{under_55_64}}</span>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="col-sm-6">
        <div class="male-female">
          <span class="col-sm-2">65+</span>
          <span>
            <nouislider [min]="someMin" [max]="someLimit" [step]="1.00" [(ngModel)]="above_65" name="above_65"></nouislider>
          </span>
          <span>%{{above_65}}</span>
        </div>
      </div>
    </fieldset>

**Comment by kiqq** [comment]
Looks like you have problem with your typescript code. How does it work with hardcoded values: 
```
  someMin: number = 0;
  someLimit: number = 100;
  male_gender: number = 50;
  under_7: number = 10;
  under_7_11: number = 10;
  under_12_17: number = 10;
  under_18_24: number = 10;
  under_25_34: number = 10;
  under_35_44: number = 10;
  under_45_54: number = 10;
  under_55_64: number = 10;
  above_65: number = 10;
```

**Comment by jahmed31** [comment]
did provide hard coded values, still the problem was that all sliders work altogether

**Comment by kiqq** [comment]
I couldn't recreate this problem. What is your version of angular, slider? 

Meanwhile you can check and play with the easiest setup of your example:
https://stackblitz.com/edit/angular-yx9g3e
maybe it let you solve your problem.
