### ISSUE TITLE
Range value beneath the Range handles while dragging the handles

### ISSUE THREAD

**Issue by shettyrahul8june** [tb/ng2-nouislider#13]
This is more of an enhancement than issue. I wanted the user to see the value beneath the handles while he/she is dragging the handles. I had to do some DOM manipulation to do so. I am not speaking about showing it in some some input.

Value beneath the handles while dragging would be a better UX and user can see while dragging what the handle value represents. It's just a suggestion and can be labelled enhancement or this ticket can be closed.

**Comment by tb** [comment]
It should be possible to activate [nouislider tooltips](http://refreshless.com/nouislider/slider-options/#section-tooltips) like this http://jsfiddle.net/leongersen/z83oz9np/2/ via `[options]="options"`.

**Comment by shettyrahul8june** [comment]
Awesome. Thanks for sharing.

**Comment by bomberblue07** [comment]
This enabled the tooltip to display, but it always displays. The issue was how to get it to display when the handle is being dragged. I would like to know how to do this as well, or if it is not currently possible, have it implemented.
