### ISSUE TITLE
Error: Metadata version mismatch for module

### ISSUE THREAD

**Issue by attrox** [tb/ng2-nouislider#137]
ERROR in Error: Metadata version mismatch for module node_modules/ng2-nouislider/src/nouislider.d.ts, found version 4, expected 3

Getting this error when doing ng build.
Not getting this error on 1.7.3

**Comment by christyTarento** [comment]
Same error even I am facing.  What's the solution for this?

**Comment by RaAleks** [comment]
Same for me.

**Comment by tb** [comment]
Last release was build with Angular 5. I was not aware it will break Angular 4. Reverted it.
