### ISSUE TITLE
ORIGINAL EXCEPTION: Error: noUiSlider: 'start' is required.

### ISSUE THREAD

**Issue by Vingtoft** [tb/ng2-nouislider#14]
I followed the instructions, but receive the following error: 

`ORIGINAL EXCEPTION: Error: noUiSlider: 'start' is required.`

Any solution?

**Comment by tb** [comment]
This is error from noUiSlider caused by setting start: ngModel while ngModel is undefined. Setting initial value for ngModel will fix it.
