### ISSUE TITLE
using angular 4 - no errors but I don't see the slider in the browser.

### ISSUE THREAD

**Issue by indiadi** [tb/ng2-nouislider#141]
I configured as the doc described. I also put the CSS include in the component:
styleUrls: ['./my.component.css',
              '../../../node_modules/nouislider/distribute/nouislider.min.css'],
I do see the slider element in the chrome developer tool.
but I don't actually see it in the browser

**Comment by kiqq** [comment]
Check again, please. https://github.com/tb/ng2-nouislider/issues/99#issuecomment-327959697

**Comment by pmoprhy** [comment]
I'm having the same issue.  I see the following element using chrome tools but the the element is not visible.

<nouislider _ngcontent-c2="" _nghost-c3="" ng-reflect-connect="true" ng-reflect-min="0" ng-reflect-max="15" ng-reflect-step="1" ng-reflect-ng-model="100,1000" ng-reflect-model="100,1000" class="ng2-nouislider ng-untouched ng-pristine ng-valid"><div _ngcontent-c3="" class="noUi-target noUi-ltr noUi-horizontal"><div class="noUi-base"><div class="noUi-connects"><div class="noUi-connect" style="transform: translate(100%, 0px) scale(0, 1);"></div></div><div class="noUi-origin" style="transform: translate(0%, 0px); z-index: 5;"><div class="noUi-handle noUi-handle-lower" data-handle="0" tabindex="0" role="slider" aria-orientation="horizontal" aria-valuemin="0.0" aria-valuemax="100.0" aria-valuenow="100.0" aria-valuetext="15"></div></div><div class="noUi-origin" style="transform: translate(0%, 0px); z-index: 4;"><div class="noUi-handle noUi-handle-upper" data-handle="1" tabindex="0" role="slider" aria-orientation="horizontal" aria-valuemin="100.0" aria-valuemax="100.0" aria-valuenow="100.0" aria-valuetext="15"></div></div></div></div></nouislider>

**Comment by kiqq** [comment]
@pmoprhy Could you show us your code and how did you import css styles?

**Comment by pmoprhy** [comment]
I added this html inside one of my own components
<nouislider  [connect]="true" [min]="0" [max]="15" [step]="1" [(ngModel)]="someRange" (ngModelChange)="onChange($event)"></nouislider>

I imported the style in my @Component 
@Component({
  selector: 'app-esri-map',
  templateUrl: './esri-map.component.html',
  styleUrls: ['./esri-map.component.css','../app/app.component.css',"../../../../node_modules/nouislider/distribute/nouislider.min.css"]
})

**Comment by kiqq** [comment]
Have you tried to import styles as in comment earlier provided:

>  to projectPath/src/styles.css add: @import "~nouislider/distribute/nouislider.min.css";

instead of your `styleUrls: ['./esri-map.component.css','../app/app.component.css',"../../../../node_modules/nouislider/distribute/nouislider.min.css"]`
??

**Comment by pmoprhy** [comment]
I tried that, get the same result. No errors in chrome dev tools, but no visible control.

**Comment by kiqq** [comment]
I honestly have no idea. It looks like css is not imported. Could you check in chrome if it is in place.
It starts with comment like this `/*! nouislider - 10.1.0 - 2017-07-28 13:09:54 */`

Could you make project in stackblitz to investigate this issue?

**Comment by pmoprhy** [comment]
I figured out what was going on. I imported the style on the app component and didn’t have
Encapsulation: ViewEncapsulation.None so it was removing the styling on my nested component.

So what worked for me was to add
@import "../../../../node_modules/nouislider/distribute/nouislider.min.css";

In my app.component.css

And change the app.component.ts to
import { Component ,ViewEncapsulation} from '@angular/core';

@Component({
    selector: 'app',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css'],
    encapsulation: ViewEncapsulation.None
})
export class AppComponent {
}
