### ISSUE TITLE
Slider Update on Click event

### ISSUE THREAD

**Issue by shankmr** [tb/ng2-nouislider#146]
How can I update slider value when someone clicks anywhere on the slider? It is working in the demo but how can I use it in my angular2/4 app?

**Comment by kiqq** [comment]
This is slider's default behaviour, so you should in slider config:
- make sure behaviour is not specified **OR**
- set behaviour explicitly `behaviour: 'tap'`

**Comment by shankmr** [comment]
I tried with setting behavior but it's not working.
here is my HTML element
<nouislider #slider [(ngModel)]="zoom" [min]="zoomMin" [max]="zoomMax" [step]="0.1" [behaviour]="tap" (ngModelChange)="updateSlideValue()"></nouislider>

**Comment by kiqq** [comment]
It looks fine.
Any errors in console?

**Comment by shankmr** [comment]
No error. It just doesn't update slider. Is there anything I can do to read click area value?

**Comment by kiqq** [comment]
https://stackblitz.com/edit/angular-cyto93
This is project with your code how does it work in your environment

**Comment by shankmr** [comment]
I got the issue. I have to override CSS and in order to achieve that I reduced the height to 2px and that's why it is not working. I changed the height and got it working. Thanks

**Comment by kiqq** [comment]
Ok no problem. Please close issue
