### ISSUE TITLE
Nouislider appearing invisible

### ISSUE THREAD

**Issue by leofiore99** [tb/ng2-nouislider#147]
I'm using ng2-nouislider with Angular 2/4 in Visual Studio 2017.
I've installed exactly how is described in the article. It's ok in my demo project, using angular-cli.

However, i'm using Visual Studio Angular Project (with Webpack) in my real project, and doing the same things, the slider doesn't appear. It works fine, perfect, but the bar is invisible. It seems like visual studio is not recognizing the "@import "~nouislider/distribute/nouislider.min.css";" in my css file. Somebody can help? Thanks!

I already copied and pasted the styles from nouislider.min.css, and it still didn't work

**Comment by leofiore99** [comment]
I copy and paste the styles from nouislider.min.css, and it still didn't work

**Comment by tb** [comment]
Check our demo folder, it uses webpack
