### ISSUE TITLE
latest version isn't on npm?

### ISSUE THREAD

**Issue by chadbr** [tb/ng2-nouislider#17]
It looks like this commit never made it to npm:

https://github.com/tb/ng2-nouislider/commit/04f989c1ee3bcd1ebee2c1ab1303706f8cc5a7ce

Any plans to push it?

Latest description on npm:
https://www.npmjs.com/package/ng2-nouislider
Note: ng2-nouislider is RC6 compatible using the new Forms API (@angular/forms)

thanks!

**Comment by tb** [comment]
@chadbr I have updated readme now and added some useful badges ;-)

Had to publish 0.9.1 to get README updated on npm.

**Comment by chadbr** [comment]
@tb have you tried using this with the latest angular-cli? I'm having a heck of a time getting the component to boot up.

I've added these to the scripts list:

      "scripts": [
        "../node_modules/nouislider/distribute/nouislider.js",
        "../node_modules/ng2-nouislider/src/nouislider.js"
      ],

but I always get a "require not defined" error on nouislider

nouislider.ts:1 Uncaught ReferenceError: require is not defined(anonymous function) @ nouislider.ts:1module.exports @ addScript.js:9185 @ nouislider.js?17e7:1__webpack_require__ @ bootstrap 6e959ae…:52972 @ scripts.bundle.js:52__webpack_require__ @ bootstrap 6e959ae…:52webpackJsonpCallback @ bootstrap 6e959ae…:23(anonymous function) @ scripts.bundle.js:1
metadata_resolver.js:628Uncaught Error: Can't construct a query for the property "ngSlider" of "RangeSliderComponent" since the query selector wasn't defined.CompileMetadataResolver.getQueryMetadata @ metadata_resolver.js:628(anonymous function) @ metadata_resolver.js:614CompileMetadataResolver.getQueriesMetadata @ metadata_resolver.js:611CompileMetadataResolver.getDirectiveMetadata @ metadata_resolver.js:169(anonymous function) @ metadata_resolver.js:268CompileMetadataResolver.getNgModuleMetadata @ metadata_resolver.js:262RuntimeCompiler._compileComponents @ runtime_compiler.js:130RuntimeCompiler._compileModuleAndComponents @ runtime_compiler.js:68RuntimeCompiler.compileModuleAsync @ runtime_compiler.js:59PlatformRef_._bootstrapModuleWithZone @ application_ref.js:302PlatformRef_.bootstrapModule @ application_ref.js:284(anonymous function) @ main.ts:12__webpack_require__ @ bootstrap 6e959ae…:52(anonymous function) @ .*$:7__webpack_require__ @ bootstrap 6e959ae…:52webpackJsonpCallback @ bootstrap 6e959ae…:23(anonymous function) @ main.bundle.js:1

**Comment by tb** [comment]
@chadbr you can try https://github.com/tb/ng2-nouislider/issues/7#issuecomment-245186438

Let me know if it worked, I will add it to README.

**Comment by chadbr** [comment]
@tb something else was wrong. Simply pulling in the node packages seems to work fine (although I haven't had time to fully test the component it's in...)

**Comment by CERkiranjoshi** [comment]
I am facing same issue with latest angular CLI ...

**Comment by narendra-agashe** [comment]
@CERkiranjoshi just remove 
 "../node_modules/nouislider/distribute/nouislider.js",
 "../node_modules/ng2-nouislider/src/nouislider.js"
from scripts array in angular-cli.json and your require is not defined error will go away!!
