### ISSUE TITLE
Slider Range is crossing maximum limit on slider button

### ISSUE THREAD

**Issue by sachinbambal** [tb/ng2-nouislider#198]
1 ) I have scenario when I am setting up minimum= 3 and maximum=20 and step=3. When slider is rendered, the max value on slider displays 21 though my max value is 20 and the modal is set to 18. In this scenario max value displayed on UI and max value in modal is miss matching, It should be consistent.

Other issue which I am facing which could be config issue is 
2 ) When I am updating max and min value of range by updateOptions it is not allowing me to set maximum value more than 100 in modal. If slider min and max is 10 and 1000 then modal updates value  till 100 and after 100 it stops updating modal but slider moves till 1000.

**Comment by avnesh-neev** [comment]
I am facing same issue, even if setting range limit negative(i.e. -10 to 10), then dynamically negative value cloned with 0 only.
