### ISSUE TITLE
I need different ranges for minimum and maximum range

### ISSUE THREAD

**Issue by gajerajimesh** [tb/ng2-nouislider#210]
We have used slider for one of my client and they need different ranges for minimum and maximum knobs like mentioned below,

Left knob of the slider can be set to any of the low values : 2, 6, 9, 12, 15, 18, 21, 25, 30, 35, 40, 45, 50, 55, 65+
Right knob of the slider can be set to any of the high values: 5, 8, 11, 14, 17, 20, 24, 29, 34, 39, 44, 49, 54, 64, 65+

Could you please suggest me, How we can implement that?

**Comment by tb** [comment]
Please check nouislider documentation, i.e. https://refreshless.com/nouislider/slider-values/#section-snap

**Comment by gajerajimesh** [comment]
@tb, I need different range of minimum and maximum. snap is not a solution for me. Could you please again review my question and provide me possible solution for the same.
