### ISSUE TITLE
Bad NPM publish

### ISSUE THREAD

**Issue by willyboy** [tb/ng2-nouislider#212]
It looks like when 1.8 was published to NPM, it published the repo instead of just the dist folder. Can you republish just the dist folder?

The problem results in having to use an import like "ng2-nouislider/dist". This would be an easy fix if we managed the import but it's in a library we use.

An alternative would be to add a "main" entry in package.json. I can open a PR for that if you want?

**Comment by communo-jschmold** [comment]
@willyboy If you can get this running, I'd totally just do a PR and link it to this thread. In the meantime, we explicitly installed `1.7.13`

`npm i ng2-nouislider@1.7.13` (no save, that'll modify your package.json file)

**Comment by jeffaxial** [comment]
If you're like me and had your version prepended with a caret, we simply ran a new build based on 1.7.x and had it break due to this change. Not good :(

**Comment by alexnoise79** [comment]
same problem here, 2 builds broken on 2 different projects

**Comment by mattlewis92** [comment]
Sorry about that folks, just published `1.8.2` with a fix! 😄
