### ISSUE TITLE
Potentially not compatible with Ivy warning

### ISSUE THREAD

**Issue by BenRacicot** [tb/ng2-nouislider#226]
After install and usage setup my terminal gives a warning:

✔ Compiled successfully.
    
    Error: node_modules/ng2-nouislider/ng2-nouislider.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (ng2-nouislider) which declares NouisliderModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
    
Thought I'd let you guys know.

**Comment by mattlewis92** [comment]
This was just done as part of https://github.com/tb/ng2-nouislider/pull/241

Please upgrade to `2.0.0` 😄
