### ISSUE TITLE
Can't apply styles

### ISSUE THREAD

**Issue by jredd** [tb/ng2-nouislider#23]
I'm using scss for my styling and I can't seem to get the styles to apply to the component. I even tried just copying and pasting the styles into my scss files thinking it might be something wrong with the import statement and it still won't apply the styles to the component... Does this have to do with the fact that components are encapsulated from each other?

**Comment by tb** [comment]
Check demo, there is custom style example [in this line](https://github.com/tb/ng2-nouislider/blob/master/demo/app.component.scss#L24)

**Comment by jredd** [comment]
I've tried that and it's not working...

**Comment by tb** [comment]
Demo is using [import](https://github.com/tb/ng2-nouislider/blob/master/demo/app.component.ts#L2). You probably use component styles. In that case, read more at https://angular.io/docs/ts/latest/guide/component-styles.html

**Comment by abcd-ca** [comment]
Using Webpack here. I'm not getting any errors. component has a width but 0 height. I've tried @import in the scss file like in the demo. Also tried using `styleUrls`. No luck, same thing.

**Comment by abcd-ca** [comment]
Update: I can get the component to show up, styled and working by copying the .css that I'm supposed to @import and paste it into my component's .scss file like so:

```
::ng-deep {
    /* pasted source of ng2-nouislider here */
}
```

Does that give you any clues as to how I can import it in a nicer way?

**Comment by martin-razus** [comment]
hey @abcd-ca , 
 I had totally same issue and your solution was the only one working. But then I tried to add it into .angular-cli.json as decsribed here: https://github.com/tb/ng2-nouislider/issues/99

and it started to work.

**Comment by Ahmed-Samir-6446** [comment]
That's not the best solution but I change in 
~nouislider/distribute/nouislider.min.css
directly

**Comment by PavolHlavaty** [comment]
For me this worked without any import:
`/deep/ .noUi-target {
    // my custom styles
}`
