### ISSUE TITLE
Change the max value after initialization?

### ISSUE THREAD

**Issue by jredd** [tb/ng2-nouislider#24]
Is it at all possible to change the max value after component has been initialized? I have a ui where I load in different lengths of data and would like those lengths to drive the max value of the slider but when I load a different set the length changes which I need to reflect in the slider as well

**Comment by jredd** [comment]
any word on this?

**Comment by tb** [comment]
You should be able to do it via public exposed [slider](https://github.com/tb/ng2-nouislider/blob/master/src/nouislider.ts#L49) by calling something like `mySlider.slider.updateOptions({range: {min: 1, max: 100}})`, see https://refreshless.com/nouislider/more/#section-update

**Comment by jredd** [comment]
Thanks for the hint, for others that might still be a little lost because I was, to get it to work I had to user the @viewChid() ability within angular to be able to modify the child component via code instead of data binding in the template. The below link helped a lot.

http://stackoverflow.com/questions/36018478/getting-a-reference-to-the-child-component-in-the-parent-component

**Comment by d-damien** [comment]
Doesn't it defeat one of the main purposes of angular : having automatically linked variables ?
