### ISSUE TITLE
NouisliderModule does not have a module def (ɵmod property) for Angular16

### ISSUE THREAD

**Issue by jbaan** [tb/ng2-nouislider#240]
I migrated my Angular project from version 15 to version 16. The compiler is working, however a runtime error occurs:

Error: NouisliderModule does not have a module def (ɵmod property)
            at transitiveScopesFor (node_modules/@angular/core/fesm2022/core.mjs:24485:11)
            at forEach (node_modules/@angular/core/fesm2022/core.mjs:24515:31)

Can you please upgrade this library to Angular16 support?

**Comment by mattlewis92** [comment]
This was just done as part of https://github.com/tb/ng2-nouislider/pull/241

Please upgrade to `2.0.0` 😄
