### ISSUE TITLE
Getting latest Value

### ISSUE THREAD

**Issue by Sk421** [tb/ng2-nouislider#25]
I can get the value only after releasing the slider.

Is there way to get the value while sliding? So that I can see the value while sliding the slider. It will make easy to select a particular value.

**Comment by tb** [comment]
ng2-nouislider is exposing [events](https://refreshless.com/nouislider/events-callbacks/), including [slide](https://github.com/tb/ng2-nouislider/blob/master/src/nouislider.ts#L105) and [update](https://github.com/tb/ng2-nouislider/blob/master/src/nouislider.ts#L97)
