### ISSUE TITLE
Can't use custom format

### ISSUE THREAD

**Issue by ryan-morris** [tb/ng2-nouislider#29]
In [noUiSlider](https://refreshless.com/nouislider/slider-read-write/) you can specify a custom format 

```
format: {
	  to: function ( value ) {
		return '$' + value;
	  },
	  from: function ( value ) {
		return value.substr(1);
	  }
	}
```

By doing a parseFloat in toValue this breaks the ability to use a custom format involving strings. I [forked](https://github.com/devenvy/ng2-nouislider/commit/1ec8ad0d98452d61b9ea84b197cf078c49f4dcd9) and got rid of it, also change the type to 'any'. I'm not sure if this is the best solution as now the default behavior of returning 2 decimal places no longer works so tests fail. 

I can create a PR but I wanted to get some feedback on what the best way to handle this would be.

**Comment by tb** [comment]
Its good idea to support it. I think you could provide default format: {to:, from:} that uses parseFloat like this: https://github.com/tb/ng2-nouislider/blob/master/src/nouislider.ts#L77

**Comment by ryan-morris** [comment]
@tb is #30 what you had in mind?

**Comment by tb** [comment]
Closed via https://github.com/tb/ng2-nouislider/pull/30
