### ISSUE TITLE
disable of slider don't work

### ISSUE THREAD

**Issue by paulharfenmeister** [tb/ng2-nouislider#32]
The noUiSlider could be [disabled](https://refreshless.com/nouislider/more/) by adding the attribute ```disabled="true"``` to the noUiSlider element, but it's not working with ng2-nouislider.

How do I achieve to disable the slider? Perhaps you could add a ```@Input() private disabled: boolean = false``` to the NouisliderComponent.

**Comment by zaikin-andrew** [comment]
Hi @tb.
Do we have any chance to see it in nearest version?

**Comment by tb** [comment]
I added it in 1.4.1, see also [demo](http://tb.github.io/ng2-nouislider/)

**Comment by yurimrm** [comment]
Hi @tb , 

Error in documentation: 

`<nouislider [min]="someMin" [max]="someLimit" [step]="0.05" [(ngModel)]="someValue" (ngModelChange)="onChange($event)" [disabled]="disabled"></nouislider>`

[disabled]="disabled" not working... Just change to:  [disabled]="true" and it's works!
