### ISSUE TITLE
Tooltips format

### ISSUE THREAD

**Issue by kkotak** [tb/ng2-nouislider#33]
Hi,

Is there a way to format the tooltips with Ng2? Not sure how I can use wNum() here. 

Thanks.

**Comment by zaikin-andrew** [comment]
Hi @kkotak 
I faced with it. I can't add wNum() in the component as module but I can use settings of the slider: 
```javascript
...
    format: {
      to: function ( value ) {
        return Math.ceil(value);
      },
      from: function ( value ) {
        return Math.ceil(value);
      }
    }
...
```

**Comment by kkotak** [comment]
Great! Thanks @zaikin-andrew. That worked like a charm. Appreciate it.
