### ISSUE TITLE
NouisliderModule is not an NgModule

### ISSUE THREAD

**Issue by jredd** [tb/ng2-nouislider#38]
I just switched over to angular cli for my project and when I try and serve the project i get the below error, thus crashing the attempt to compile the application so it can be served

`NouisliderModule is not an NgModule`

**Comment by hisham** [comment]
I am getting this too. Did you find a solution @jredd?

**Comment by hisham** [comment]
I was able to resolve this by importing NouisliderComponent and adding that to the app's declarations. Did not do anything with NouisliderModule.

**Comment by daBishMan** [comment]
`import { AppComponent } from './app.component';
import { NouisliderComponent  } from 'ng2-nouislider';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    NouisliderComponent
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }`

And I still get ERROR in NouisliderComponent is not an NgModule

am I doing something wrong?

**Comment by hisham** [comment]
Put NouisliderComponent in declarations not imports.

**Comment by daBishMan** [comment]
@hisham  thanks you so much for the quick reply and help, that worked for me.

**Comment by daBishMan** [comment]
@hisham do you have a basic angular-cli project that I can take a look at to see how you have used this please ?

**Comment by hisham** [comment]
Not publicly no, but it was pretty east to use and setup.

**Comment by daBishMan** [comment]
I added `@import "../node_modules/nouislider/distribute/nouislider.min.css";` to my css file, and I changed it to component like you suggested, but when I run, this is a new angular-cli  (latest on CLI) project with nothing else in it, and I get 
`zone.js:405Unhandled Promise rejection: Failed to load ../node_modules/nouislider/distribute/nouislider.min.css ; Zone: <root> ; Task: Promise.then ; Value: Failed to load ../node_modules/nouislider/distribute/nouislider.min.css undefined
consoleError @ zone.js:405
_loop_1 @ zone.js:434
drainMicroTaskQueue @ zone.js:438
ZoneTask.invoke @ zone.js:349
2017-01-10 13:04:34.585 zone.js:407Error: Uncaught (in promise): Failed to load ../node_modules/nouislider/distribute/nouislider.min.css
    at resolvePromise (zone.js:486) [<root>]
    at resolvePromise (zone.js:471) [<root>]
    at :4200/vendor.bundle.js:88804:17 [<root>]
    at Zone.runTask (zone.js:151) [<root> => <root>]
    at drainMicroTaskQueue (zone.js:418) [<root>]
    at XMLHttpRequest.ZoneTask.invoke (zone.js:349) [<root>]`

**Comment by hisham** [comment]
Looks like a path issue. Try to add that css file under "styles" in your angular-cli.json instead of through @import. This is what I got: 
      
`"styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.min.css",
        "../node_modules/nouislider/distribute/nouislider.min.css"]`

**Comment by daBishMan** [comment]
so bootstrap is needed as dependency?  I missed that.  I will try it.  Thanks again for your help

**Comment by hisham** [comment]
Doesn't look like it. I was just using bootstrap in my project for other things.

**Comment by jredd** [comment]
I don't think you have too? If you want it styled and all that I think it's needed, but you could just look at all the classes and create your own... I ended up overriding a decent number of mine anyways. @hishman sorry for the slow response, I wasn't able to overcome the issue and thanks for sharing your solution. Haven't tried it yet.

**Comment by hisham** [comment]
Yeah no bootstrap needed. You can see the app i did using nouislider here btw: http://cora-patient.snapdx.co/. Those sliders are nouisliders with our own css styles applied. 

We should probably close this ticket as @jredd's question has now been answered.

**Comment by jredd** [comment]
@hisham agreed on closing!

**Comment by daBishMan** [comment]
@hisham @jredd 

I know you closed this issue, but I am still struggling with getting it to work.  I created a repo https://github.com/daBishMan/slider it is public with both of you as contributors.

Can you help?

**Comment by hisham** [comment]
Sure. What specific issue are you running into now?

**Comment by daBishMan** [comment]
I can not get the UI to show, and it does not run, there is something wrong in my setup.   I am not sure what it is.

**Comment by hisham** [comment]
Usually in this case there is an error in the browser console you can see.

**Comment by karan83** [comment]
@daBishMan, I had same issue & i have fixed UI issue by adding css file in angular-cli.json.
`"styles": [
      "styles.css",
      "../node_modules/nouislider/distribute/nouislider.min.css"
    ]`
I have cloned your repository and it's working fine by adding css file.

**Comment by daBishMan** [comment]
@karan83 I did the same think you said 
`      "styles": [
        "styles.css",
        "../node_modules/nouislider/distribute/nouislider.min.css" 
      ],`
in my angular-cli.json. 

I added the following html
`<nouislider [connect]="true" [min]="0" [max]="15" [(ngModel)]="someRange"></nouislider>`

when I run I get 

> EXCEPTION: Error in ./AppComponent class AppComponent - inline template:4:50 caused by: noUiSlider (9.2.0): 'start' is required.

> error_handler.js:56Error: noUiSlider (9.2.0): 'start' is required.
    at http://localhost:4200/vendor.bundle.js:82478:12 [angular]
    at Array.forEach (native) [angular]
    at testOptions (http://localhost:4200/vendor.bundle.js:82472:22) [angular]
    at Object.initialize [as create] (http://localhost:4200/vendor.bundle.js:83751:17) [angular]
    at NouisliderComponent.ngOnInit (http://localhost:4200/vendor.bundle.js:81432:34) [angular]
    at Wrapper_NouisliderComponent.ngDoCheck (/AppModule/NouisliderComponent/wrapper.ngfactory.js:180:53) [angular]
    at CompiledTemplate.proxyViewClass.View_AppComponent0.detectChangesInternal (/AppModule/AppComponent/component.ngfactory.js:73:33) [angular]
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4200/vendor.bundle.js:74489:14) [angular]
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:74684:44) [angular]
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:4200/vendor.bundle.js:74474:18) [angular]
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.detectChangesInternal (/AppModule/AppComponent/host.ngfactory.js:29:19) [angular]
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4200/vendor.bundle.js:74489:14) [angular]
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:74684:44) [angular]
    at ViewRef_.detectChanges (http://localhost:4200/vendor.bundle.js:55251:20) [angular]

**Comment by daBishMan** [comment]
@karan83 I made you a contributor on my repo, can you check in what you have working please with sugar on top please.

**Comment by jredd** [comment]
I was able to finally sit down and do the changes @hisham suggested and it worked just fine for me. @daBishMan I can't look at it right now but if the issue hasn't been resolved this evening I'll try and take a peek at it.

**Comment by ryan-morris** [comment]
I began having this issue. When I move NouisliderModule to declarations instead of imports I see `Unexpected module 'NouisliderModule' declared by the module 'MyModule'`

**Comment by jovanialferez** [comment]
@ryan-morris you no longer have to use `NouisliderModule` but rather have `NouisliderComponent` in you declarations.

**Comment by hemanrnjn** [comment]
@daBishMan Did you resolve the problem? I am also getting the same issue.

**Comment by daBishMan** [comment]
@hemanrnjn sorry I was not able to to fix it.

**Comment by sqnkov** [comment]
@hisham , hello!

Can you post a simple example of how stuff should look like?

```
// Angular Imports
import { NgModule } from '@angular/core';

// Range sliders
import { NouisliderModule } from 'ng2-nouislider';

// This Module's Components
import { GetQuoteComponent } from './get-quote.component';

@NgModule({
    imports: [
        NouisliderModule,
    ],
    declarations: [
        GetQuoteComponent,
    ],
    exports: [
        GetQuoteComponent,
    ]
})
export class GetQuoteModule {

}
```

And my component looks like:

```
import { Component } from '@angular/core';

@Component({
    moduleId: module.id,
    selector: 'get-quote',
    templateUrl: 'get-quote.component.html',
})
export class GetQuoteComponent {

    someRange2config: any = {
        behaviour: 'drag',
        connect: true,
        margin: 1,
        limit: 5, // NOTE: overwritten by [limit]="10"
        range: {
            min: 0,
            max: 20
        },
        pips: {
            mode: 'steps',
            density: 5
        }
    };

}
```

Markup looks like:

` <nouislider [config]="someRange2config" [limit]="10" [(ngModel)]="someRange2"></nouislider>`

**Comment by singhpuja11** [comment]
Any update on the same. Have imported NouisliderComponent in app.module.ts and in the app.component.ts. Added css file in ,angular-cli.json. Am not getting any error, but slider component is not showing up. Please let me know what am I missing, am using @angular/cli 1.0.0.

**app.module.ts**
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';
import { NouisliderComponent } from 'ng2-nouislider';
@NgModule({
  declarations: [
    AppComponent,
    NouisliderComponent  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    ReactiveFormsModule,
    
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

**app.component.ts**
import { Component, Input, OnInit, AfterViewInit }          from '@angular/core';
import { Validators, FormGroup, FormBuilder, FormArray, FormControl }    from '@angular/forms';
import { NouisliderComponent } from 'ng2-nouislider';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit{
  title = 'app works!';
  form1: FormGroup;
  form2: FormGroup;
  constructor(protected fb: FormBuilder) {
        //console.log("QuestionBaseFormComponent Constructor:", this.children);
    }

  ngOnInit() {
    this.form1 = this.fb.group({ 'single': [ 10 ] });
    console.log(this.form1);
    this.form2 = this.fb.group({ 'range': [ [ 2, 8 ] ] });
  }
}
**app.component.html**
<h1>
  {{title}}
</h1>

<nouislider [connect]="true" [min]="0" [max]="15" [(ngModel)]="someRange"></nouislider>
<form [formGroup]="form1">
    <nouislider [min]="0" [max]="20" [step]="0.5" [formControl]="form1.controls.single"></nouislider>
</form>

<form [formGroup]="form1">
    <nouislider [min]="0" [max]="20" [step]="0.5" [formControl]="form2.controls.range"></nouislider>
</form>

.angular-cli.json
"styles": [
        "styles.css",
         "../node_modules/nouislider/distribute/nouislider.min.css" 
      ],

**Comment by singhpuja11** [comment]
Got it working, thanks. Stopped the server and restarted. Have another query as how do I shown the slider value as it moves? Thanks.

**Comment by errorx666** [comment]
Declaring the component instead of importing the module seems like a workaround not a fix.

**Comment by visar1897** [comment]
I fixed this by change the import path of the module:
`import {NouisliderModule} from 'ng2-nouislider'` => `import {NouisliderModule} from 'ng2-nouislider/src/nouislider'`

**Comment by errorx666** [comment]
That's importing the source TypeScript instead of the transpiled bundle files, which I guess is fine.

**Comment by hemantpiliyagate6** [comment]
@visar1897   Thank You :)

**Comment by AbhI9519** [comment]
I think this is version issue, this work fine for me please go through once if you still getting the error 
npm i --save nouislider ng2-nouislider@1.6.2
