### ISSUE TITLE
Step input is bugged

### ISSUE THREAD

**Issue by chrillewoodz** [tb/ng2-nouislider#40]
When setting the step to `1`, sometimes you get values of like 7331.000000001.

**Comment by tb** [comment]
This is fixed.

**Comment by BearandYoon** [comment]
Hi @tb 
I am using this component on my Angular 2 project and normally it works for me.
But I have a problem.
When I set the step as more than 1 (for ex: step: 1000), it doesn't work and web browser is not responding.

My config is :
 this.priceRange2config = {
      behaviour: 'drag',
      connect: true,
      step: 1000,
      range: {
        min: 0,
        max: 400000
      },
      pips: {
        mode: 'steps',
        density: 5
      }
    };

And I would like to set NoMax on Range. is this possible?
