### ISSUE TITLE
Question: does this work with latest angular-cli and angular 2.2x?

### ISSUE THREAD

**Issue by daBishMan** [tb/ng2-nouislider#41]
Have you tried to run this using angular cli and latest version of angular ?

**Comment by hisham** [comment]
yes I used it in this environment and it is working.

**Comment by daBishMan** [comment]
@hisham @tb   Thank you for your response, but is there a way to share what you have done to get it working.  Sorry if my question is elementary, but any help you can provide is greatly appreciated.

**Comment by itswadesh** [comment]
can you share the code for angular-cli and reactive forms
