### ISSUE TITLE
EXCEPTION: noUiSlider: must pass a formatter for all handles. (When Tooltips on)

### ISSUE THREAD

**Issue by ravi-logiciel** [tb/ng2-nouislider#45]
(When Tooltips on)
##Configs

ageRangeConfigs: any = {
        behaviour : 'drag',
        connect   : true,
        tooltips  : [ true, true ],
        // start     : [20, 40],
        keyboard  : true,
        step      : 1,
        pageSteps : 1,
        range     : {
            min     : 0,
            max     : 100
        },
        pips      : {
            mode    : 'count',
            density : 5,
            values  : 5,
            stepped : true,
        }
    };
*********

##Error

ORIGINAL EXCEPTION: noUiSlider: must pass a formatter for all handles.
ErrorHandler.handleError @ error_handler.js:49
next @ application_ref.js:272
schedulerFn @ async.js:82
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:74
NgZone.triggerError @ ng_zone.js:278
onHandleError @ ng_zone.js:257
ZoneDelegate.handleError @ zone.js:236
Zone.runTask @ zone.js:157
drainMicroTaskQueue @ zone.js:401
ZoneTask.invoke @ zone.js:339
error_handler.js:52 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:52
next @ application_ref.js:272
schedulerFn @ async.js:82
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:74
NgZone.triggerError @ ng_zone.js:278
onHandleError @ ng_zone.js:257
ZoneDelegate.handleError @ zone.js:236
Zone.runTask @ zone.js:157
drainMicroTaskQueue @ zone.js:401
ZoneTask.invoke @ zone.js:339
error_handler.js:53 Error: noUiSlider: must pass a formatter for all handles.
    at Object.testTooltips [as t] (http://localhost:4200/main.bundle.js:77114:11)
    at http://localhost:4200/main.bundle.js:77269:16
    at Array.forEach (native)
    at testOptions (http://localhost:4200/main.bundle.js:77257:22)
    at Object.initialize [as create] (http://localhost:4200/main.bundle.js:78522:17)
    at NouisliderComponent.ngOnInit (http://localhost:4200/main.bundle.js:76219:34)
    at Wrapper_NouisliderComponent.detectChangesInInputProps (/NouisliderModule/NouisliderComponent/wrapper.ngfactory.js:169:53)
    at _View_AddCampaignComponent0.detectChangesInternal (/AppModule/AddCampaignComponent/component.ngfactory.js:1714:34)
    at _View_AddCampaignComponent0.AppView.detectChanges (http://localhost:4200/main.bundle.js:63926:14)
    at _View_AddCampaignComponent0.DebugAppView.detectChanges (http://localhost:4200/main.bundle.js:64031:44)
ErrorHandler.handleError @ error_handler.js:53
next @ application_ref.js:272
schedulerFn @ async.js:82
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:74
NgZone.triggerError @ ng_zone.js:278
onHandleError @ ng_zone.js:257
ZoneDelegate.handleError @ zone.js:236
Zone.runTask @ zone.js:157
drainMicroTaskQueue @ zone.js:401
ZoneTask.invoke @ zone.js:339
error_handler.js:56 ERROR CONTEXT:

**Comment by davyzhang** [comment]
```typedscript
<nouislider [connect]="true" [step]="1" [min]="0" [max]="100" [tooltips]="[true,true]" [formControl]="cells"></nouislider>
```
with
```
cells: new FormControl([5,15]),
```

works for me

**Comment by jiayihu** [comment]
I'm having the same issue @tb and it should work also without `FormControl` as shown in demos
