### ISSUE TITLE
Custom format does not work with tooltips

### ISSUE THREAD

**Issue by berndartmueller** [tb/ng2-nouislider#47]
Hello,

I'm struggling with getting my custom formatter to work with tooltips. I always receive an `EXCEPTION: noUiSlider: 'tooltips' must be passed a formatter or 'false'` error.

`<nouislider *ngIf="isBrowser" [connect]="true" [step]="1" [min]="1" [max]="20" [tooltips]="[roomsFormatter, roomsFormatter]" [ngModel]="roomsRange" (change)="onRoomsChange($event)"></nouislider>`

In my angular component I create the formatter as following: 

`roomsFormatter: NouiFormatter = {
    to: (value: number): string => {
      return value + ' Zimmer';
    },
    from: (value: string): number => {
      return parseFloat(value.split(' Zimmer')[0]);
    }
  };`

Thanks for any help!

**Comment by tb** [comment]
@berndartmueller Pass roomsFormatter via `[format]=`
