### ISSUE TITLE
How to refresh range values?

### ISSUE THREAD

**Issue by cimey** [tb/ng2-nouislider#49]
hi, 

After creating slider, i am trying to update range values but new range values are not reflected to view. after i click to slider, new values are reflected.
`<nouislider 
[config]="sliderConfig" 
[step]="0.5" 
[formControl]="filterForm.controls['range']">
</nouislider>
`

`this.sliderConfig.range = { min: this.minPrice, max: this.maxPrice };
`

**Comment by jovanialferez** [comment]
see my comment here: https://github.com/tb/ng2-nouislider/issues/55

**Comment by tb** [comment]
Since 1.6.0 you an update ranges with `[min]="someMin" [max]="someLimit"`, check [demo](http://tb.github.io/ng2-nouislider/)
