### ISSUE TITLE
Slider not updated when inputs are updated

### ISSUE THREAD

**Issue by alcfeoh** [tb/ng2-nouislider#55]
ng2-nouislider does not implement ngOnChanges. As a result, change detection does not happen when input parameters change. This should really be fixed are bindings are supposed to be bindings, not just a one-off initialization thing.

Hint: If you just rename ngOnInit to ngOnChanges, this might be all you need to fix the issue.

**Comment by prateek0103** [comment]
@alcfeoh have you tried this fix? There is no point of this component if it doesn't update with bindings

**Comment by alcfeoh** [comment]
@prateek0103 I haven't tried the fix yet. I agree with you though, the component is pretty much useless without proper bindings in place.

**Comment by prateek0103** [comment]
@alcfeoh Is there any way to implement `ngOnChanges` in the class of the component where I am using this? Something like forced re-initialization of this module with new values.

**Comment by alcfeoh** [comment]
I ended up writing my own slider. Another option would be to copy paste the source code of their component and add the ngOnChanges method.

**Comment by gmazzamuto** [comment]
shouldn't you use `ngOnModelChange`? Please see the [demo page](http://tb.github.io/ng2-nouislider/), everything seems to be working as expected.

**Comment by alcfeoh** [comment]
ngModelChange is to get notified of slider updates. I looked at the demo code and they use a nasty trick to access the slider component:

`const control = <FormControl>this.form2.controls['range'];`

And then they set values to the control object.  Still the `@Input` don't behave the way they should.

**Comment by gmazzamuto** [comment]
I see, you mean `@Input` parameters such as `min`, `max`, `step`, etc.

If you got it working and if you don't mind, please submit a PR.

**Comment by sushiie** [comment]
Any update on this?

**Comment by jovanialferez** [comment]
Found a way:

First, reference you slider as a child view of your component:
`@ViewChild('mySlider') public mySlider: NouisliderComponent`

then call `updateOptions` (@see https://refreshless.com/nouislider/more/#section-update):
`this.mySlider.slider.updateOptions({
  range: {
          min: 5,
          max: 96
        }
})`

Note that `slider` here is the `noUiSlider` instance created as per source code. HTH. :)

**Comment by sushiie** [comment]
@jovanialferez, thanks man. This solved the problem.

**Comment by jovanialferez** [comment]
Glad it helped. :)

**Comment by davidcalleja** [comment]
@jovanialferez can you put a more complete example, please?

**Comment by ejasarevic** [comment]
@jovanialferez - Thanks!!!

**Comment by jovanialferez** [comment]
@adityaitsrkr kinda busy now. sorry. :(
