### ISSUE TITLE
Weird / wrong behavior of the ngModel

### ISSUE THREAD

**Issue by sconix** [tb/ng2-nouislider#57]
The ngModel does not work as you would expect it to. It works correctly when the component is initialized when there is no change event, but if the value is changed programmatically after initialization there is a change event which causes problems since you can not know which event is from user changing the value and which is made programmatically.

For simple test I used this:
<input [ngModel]="value || 'test'" (ngModelChange)="onInputChange($event)"/>
<nouislider ... [ngModel]="value || 0" (ngModelChange)="onValueChange($event)"></nouislider>

When changing the value variable input did not send change event as it should be, but the nouislider did send an event.

**Comment by BearandYoon** [comment]
Hi @sconix 
I faced the same issue.
This issue has been solved?
