### ISSUE TITLE
No longer works with Angular2 rc.6

### ISSUE THREAD

**Issue by russcarver** [tb/ng2-nouislider#6]
Getting this error on Angular2 rc.6:

zone.js:484 Unhandled Promise rejection: TypeError: core_1.Provider is not a constructor
	    at Object.eval (http://localhost:3001/vendor/ng2-nouislider/src/nouislider.js:26:41)

This comes from:

var NOUISLIDER_CONTROL_VALUE_ACCESSOR = new core_1.Provider(forms_1.NG_VALUE_ACCESSOR, {
    useExisting: core_1.forwardRef(function () { return Nouislider; }),
    multi: true
});

where core_1 = require('@angular/core');

Apparently in rc.6, @angular/core/index has no exported member 'provide'

**Comment by tb** [comment]
@fixed in 0.6.0 release

**Comment by russcarver** [comment]
When will 0.6.0 be released?

**Comment by tb** [comment]
0.6.0 was published to npm couple hours ago.

In the mean time I have also worked on tests... and changed directive to component. Since its breaking change, I have published it as 0.7.0.

With 0.7.0 you need to do is to change: `<div nouislider ...>` to `<nouislider ...>`
