### ISSUE TITLE
loading without system js

### ISSUE THREAD

**Issue by kakarias** [tb/ng2-nouislider#61]
Hi is there possibility run it without system js? it throws me an error that i need noUiSlider (9.2.0).
I use basic angular-cli project.

EXCEPTION: Uncaught (in promise): Error: Error in ./FilterComponent class FilterComponent - inline template:30:55 caused by: noUiSlider (9.2.0): 'start' is required.
Error: Error in ./FilterComponent class FilterComponent - inline template:30:55 caused by: noUiSlider (9.2.0): 'start' is required.

**Comment by tb** [comment]
@kakarias Did you provide data? The error might root in https://github.com/tb/ng2-nouislider/blob/master/src/nouislider.ts#L91

**Comment by kakarias** [comment]
Sorry im so stupid, i provide the data but to another property. i didnt realise that error is regarding to my fault.
