### ISSUE TITLE
Change limit dynamically

### ISSUE THREAD

**Issue by smikey** [tb/ng2-nouislider#64]
Is it possible to change the limit of the slider dynamically? As I see it's set on ngInit() but I need to change it later because I have different sliders influencing each other?

I'm trying to set it this way:
`<nouislider [connect]="[false,true, false]" [limit]="sliderPointsLeft" [min]="0" [max]="1000" [step]="1" [formControl]="theForm.controls.range" (update)="sliderUpdate(item.id,$event)"></nouislider>`

So sliderPointsLeft is changed any time some of the sliders is used.

**Comment by tb** [comment]
It will require adding https://angular.io/docs/ts/latest/api/core/index/OnChanges-class.html and using https://refreshless.com/nouislider/more/#section-update Can you do PR with it?

**Comment by jovanialferez** [comment]
see my comment here: https://github.com/tb/ng2-nouislider/issues/55

**Comment by davejohncole** [comment]
I have hit the same limitation with this component, but as I have just started using angular so do not have the skills necessary to fix this myself.

Looking at the documentation here https://refreshless.com/nouislider/more/ it appears that the wrapped control supports the capability.

**Comment by IgorceJovanoski** [comment]
Hey,
just a a shout for changing dynamically the range for angular2 or higher, I used the advices with the view child and update options tl;dr; 
front:
`<nouislider [connect]="true" [step]="1" [min]="modelMonthlyCost.min" [max]="modelMonthlyCost.max" [(ngModel)]="monthlyCostRange" [ngModelOptions]="{standalone: true}" (change)="changeMonthlyCost()" #monthlyCostSlider></nouislider>` 

back:
`@ViewChild('monthlyCostSlider') public monthlyCostSlider: NouisliderComponent`
.
.
.
`this.monthlyCostRange = [+newModelMonthlyCost.min, +newModelMonthlyCost.max];
if (this.monthlyCostSlider.slider) this.monthlyCostSlider.slider.updateOptions({ start: [+newModelMonthlyCost.min, +newModelMonthlyCost.max], range: { min: +newModelMonthlyCost.min, max: +newModelMonthlyCost.max } });
`

Hope it helps, works for me

**Comment by Talanoff** [comment]
You can do like this:
this.priceSliderRef.slider.set([+valueToSet1, +valueToSet2]);

**Comment by adityaitsrkr** [comment]
Hi Talanoff
Can you pls post ur code.
How r u getting the nouislider objects.
Like update option.
Can you pls help
