### ISSUE TITLE
using Nouislider throws error "'start' is required"

### ISSUE THREAD

**Issue by NikasZalias** [tb/ng2-nouislider#66]
I'm having issues with using nouislider... I'm creating chrome extenson with angular2 and using webpack.

In package.json I added these packages:

```
"ng2-nouislider": "1.5.2",
"nouislider": "9.2.0"
```

then in my app.module.ts i imported nouislider and added to declarations like this:

```
import { NouisliderComponent } from 'ng2-nouislider';

@NgModule({
  imports:      [ ... ],
  declarations: [ ... , NouisliderComponent ],
  bootstrap:    [ AppComponent ]
})
```
also in my component I added css file:

```
@Component({
    ....,
    styleUrls: ['"../node_modules/nouislider/distribute/nouislider.min.css"']
})
```

and in my html file I added simple slider from example:

`<nouislider [min]="0" [max]="10" [step]="0.05" [disabled]="disabled"></nouislider>`

when I compile and try to run I get the following error:

> EXCEPTION: Uncaught (in promise): Error: noUiSlider (9.2.0): 'start' is required.
> Error: noUiSlider (9.2.0): 'start' is required.
>     at chrome-extension://xxx/src/page-sidebar/dist/vendor.bundle.js:109854:12 [angular]
>     at Array.forEach (native) [angular]
>     at testOptions (chrome-extension://xxx/src/page-sidebar/dist/vendor.bundle.js:109848:22) [angular]
>     at Object.initialize [as create] (chrome-extension://xxx/src/page-sidebar/dist/vendor.bundle.js:111127:17) [angular]
>     at NouisliderComponent.ngOnInit (chrome-extension://xxx/src/page-sidebar/dist/vendor.bundle.js:86174:34) [angular]
>     at Wrapper_NouisliderComponent.ngDoCheck (/AppModule/NouisliderComponent/wrapper.ngfactory.js:159:73) [angular]
>     at CompiledTemplate.proxyViewClass.View_ParsingComponent0.detectChangesInternal (/AppModule/ParsingComponent/component.ngfactory.js:393:34) [angular]
>     at CompiledTemplate.proxyViewClass.AppView.detectChanges (chrome-extension://xxx/src/page-sidebar/dist/vendor.bundle.js:101152:14) [angular]
>     at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (chrome-extension://xxx/src/page-sidebar/dist/vendor.bundle.js:101137:18) [angular]
>     at CompiledTemplate.proxyViewClass.View_ParsingComponent_Host0.detectChangesInternal (/AppModule/ParsingComponent/host.ngfactory.js:27:19) [angular]
>     at CompiledTemplate.proxyViewClass.AppView.detectChanges (chrome-extension://xxx/src/page-sidebar/dist/vendor.bundle.js:101152:14) [angular]
>     at ViewRef_.detectChanges (chrome-extension://xxx/src/page-sidebar/dist/vendor.bundle.js:62411:20) [angular]
>     at RouterOutlet.activate (chrome-extension://xxx/src/page-sidebar/dist/vendor.bundle.js:68699:42) [angular]
>     at ActivateRoutes.placeComponentIntoOutlet (chrome-extension://xxx/src/page-sidebar/dist/vendor.bundle.js:25211:16) [angular]
> ErrorHandler.handleError @ error_handler.js:54
> error_handler.js:59 ORIGINAL STACKTRACE:
> ErrorHandler.handleError @ error_handler.js:59

What I am doing wrong? How to fix this issue?

**Comment by tb** [comment]
@NikasZalias you miss ngModel

**Comment by NikasZalias** [comment]
@tb I have ngModel, app works fine, I just didn't add here other imports. Just slider doesn't work

**Comment by Rachana-Mahajan** [comment]
I am also facing the same issue.
I have imported NouisliderModule in app.module.ts and declared the same module in imports section.

Now my html file has:
**<nouislider [connect]="true" [min]="0" [max]="15" [step]="1" [(ngModel)]="someRange"></nouislider>**

where, someRange: [ 2, 10 ];

On running this, I get the following error:
***********************************************************************************************************
EXCEPTION: Error in ./AppComponent class AppComponent - inline template:4:61 caused by: noUiSlider (9.2.0): 'start' is required.
ErrorHandler.handleError @ error_handler.js:54
*************************************************************************************************************

How to get it working?

**Comment by abdallahmaali** [comment]
i have same problem too
