### ISSUE TITLE
caused by: noUiSlider (9.2.0): 'start' is required.

### ISSUE THREAD

**Issue by theromie** [tb/ng2-nouislider#67]
`<nouislider [connect]="true" [min]="0" [max]="15" [step]="1" [(ngModel)]="someRange"></nouislider>`
`import { NouisliderComponent } from 'ng2-nouislider';`

**Comment by emonidi** [comment]
I get the same error. Any ideas what am I doing wrong?

**Comment by spredemann** [comment]
It's because of this line:
https://github.com/tb/ng2-nouislider/blob/master/src/nouislider.ts#L91

Your someRange probably doesn't have a default value or it doesn't exist. Check for spelling.

**Comment by ValerioBulla** [comment]
I have an app with some optional inputs, and since their initial value is undefined I get this error as well. Any chance I could get this to work without a default value?

**Comment by tb** [comment]
@ValerioBulla If input is optional and you use ngIf to hide it you wont get this error.

**Comment by ValerioBulla** [comment]
@tb I tried using ngIf before, but of course it prevents using the slider to input a value since it's hidden.

**Comment by rach12345** [comment]
@theromie 
Define your someRange in corresponding ts file as:
**someRange=[1, 50]**

This is the range you want your slider to cover. You might be missing either the syntax/spelling of this.

**With ng2-nouislider, the major reason of getting "9.2.0 start is required" error is, the binding of [(ngModel)]. Once this is resolved, I believe your slider should work fine!**

**Comment by theromie** [comment]
thanks @rach12345 its working by defining in component

**Comment by premiumwd** [comment]
nope not working. or any clear direction.

**Comment by gp187** [comment]
Still not working

**Comment by parthdevloper** [comment]
Hello guyz,

> **Just use the below-mentioned code, It will help to resolve the error:**

`HTML:`
`<nouislider [min]="5" [max]="10" [step]="0.05" [(ngModel)]="someRange" ></nouislider>`

`TS:`

` someRange=[6, 7]`
  `constructor() { }`
  `ngOnInit(): void {`
 ` }`

`module.TS:`

`import { NouisliderModule } from 'ng2-nouislider';`

`@NgModule({`
`  imports: [`
 `   CommonModule,`
`    NouisliderModule`
 ` ]`
`})`

Let me know how it works with you... :+1:
