### ISSUE TITLE
Angular CLI configuration

### ISSUE THREAD

**Issue by hotkebab99** [tb/ng2-nouislider#69]
Hello,
Angular CLI uses Webpack and I can't make ng2-nouislider working... Can you help me please ?

Here what I done :

**Install librairies**

`npm i --save nouislider ng2-nouislider`

**Import module in my module**

`import { NouisliderModule } from 'ng2-nouislider';`

```
@NgModule({
  imports: [
    CommonModule,
    PhtCommonModule,
    NouisliderModule,
  ],
```

**CSS import in .angularcli.json**

```
"styles": [
        "styles.css",
        "../node_modules/nouislider/distribute/nouislider.min.css",
        "../node_modules/font-awesome/css/font-awesome.min.css",
        "../node_modules/bootstrap/dist/css/bootstrap-theme.min.css",
        "../node_modules/bootstrap/dist/css/bootstrap.min.css"
      ],

```

So I made a new component in my template with
```
<nouislider [config]="sliderConfig" 
            [(ngModel)]="train.speed" 
            (ngModelChange)="console.log('hi')"></nouislider>
{{ train.speed }}
```

I can see the slider and the init value is correctly set to `train.speed` but when I change the slider, the model is not updated and no 'hi' or error messafe in the console.

I tried to import the 2 js files quoted in the doc in my .angular-cli.json :
```
"scripts": [
        "../node_modules/nouislider/distribute/nouislider.js",
        "../node_modules/ng2-nouislider/src/nouislider.js"
      ],
```

With that, when I'm loading my app, I have the error :

```
nouislider.ts:1Uncaught ReferenceError: require is not defined
    at eval (eval at webpackJsonp.359.module.exports (addScript.js:9), <anonymous>:11:18)
    at eval (<anonymous>)
    at webpackJsonp.359.module.exports (addScript.js:9)
    at Object.382 (nouislider.js?bfdd:1)
    at __webpack_require__ (bootstrap a16ca03…:52)
    at Object.659 (scripts.bundle.js:52)
    at __webpack_require__ (bootstrap a16ca03…:52)
    at webpackJsonpCallback (bootstrap a16ca03…:23)
    at scripts.bundle.js:1
```
The error is linked to that line in nouislider.ts :
`import * as noUiSlider from 'nouislider';`

Thank you so much for your help !

**Comment by hotkebab99** [comment]
Hello,
Found the problem.
I forgot to include a module :
`import { FormsModule }   from '@angular/forms';`

Everything is ok now !

**Comment by JustinSchneider** [comment]
@hotkebab99 I'm seeing this issue as well. I already have FormsModule imported in my app.module.ts, and have tried adding it to any component that uses nouiSlider, but no luck.

**Comment by hotkebab99** [comment]
@JustinSchneider  Don't know why it doesn't work for you... Do you have any message ? If you have all I wrote and the FormsModule imported, it should work.
Maybe try to open à new issue if not.
