### ISSUE TITLE
Angular 4 support?

### ISSUE THREAD

**Issue by yzhogoliev** [tb/ng2-nouislider#73]

**Comment by yzhogoliev** [comment]
To be honest, it works with the angular 4, but npm's warnings are a little bit disturbing.

**Comment by yankos** [comment]
I use angular 4.0.0 with ng2-nouislider 1.5.0 without any problem.

**Comment by TVrijdag** [comment]
In our project, we use npm shrinkwrap to lock versions of dependencies. However, this does not work anymore with Angular 4 because of these invalid peer warnings.

**Comment by Karamazov747** [comment]
We use shrinkwrap also and we face the same issue:
`npm ERR! peer invalid: @angular/common@^2.0.0, required by ng2-nouislider@1.6.0
npm ERR! peer invalid: @angular/core@^2.0.0, required by ng2-nouislider@1.6.0`

**Comment by tb** [comment]
Fixed via https://github.com/tb/ng2-nouislider/pull/80 by @amenophis Published as 1.6.1
