### ISSUE TITLE
Pips update

### ISSUE THREAD

**Issue by piskula** [tb/ng2-nouislider#74]
Hi,
Is there some way how to easily update Pips? Updating range works really nice, but pips stuck at initial status.
Thanks

**Comment by DecampsRenan** [comment]
I face the same problem

**Comment by piskula** [comment]
I done it, but the way that I implemented my own scale, which gets
* start point
* step
* number of points
as @Input parameters
https://github.com/piskula/timeline-slider/blob/master/src/app/timeline-scale/timeline-scale.component.ts

**Comment by jonigl** [comment]
Hi, this problem was closed, but the original problem is still happening. If you update the range, the pips remain in the initial state.
Thanks!
