### ISSUE TITLE
Doesn't load

### ISSUE THREAD

**Issue by kapotutikapi** [tb/ng2-nouislider#75]
Hi, 

I'm kinda new in NG2 and I'm trying to make your slider work. Sadly I stuck on this error message. Any idea how to fix it?

Exception: Call to Node module failed with error: Error: Uncaught (in promise): TypeError: this.el.nativeElement.querySelector is not a function
 TypeError: this.el.nativeElement.querySelector is not a function
 at NouisliderComponent.ngOnInit

Appears after I add this into one of components: "<nouislider [connect]="true" [min]="0" [max]="15" [(ngModel)]="someRange"></nouislider>"

**Comment by rach12345** [comment]
Can you tell how have you defined someRange?

**Comment by kapotutikapi** [comment]
Actually found issue. It was caused by SSR (server side rendering). You have to turn it off. 
FYI:
someRange: number = [ 0, 15];
