### ISSUE TITLE
Reactive Forms and [disabled]: Angular Warning

### ISSUE THREAD

**Issue by dhardtke** [tb/ng2-nouislider#76]
Hey,

I am using the provided component like this:
```html
<nouislider [style.height]="renderOrientation == 'VERTICAL' ? answerForm.answers.length * 37.5 + 'px' : 'auto'" [formControl]="formGroup.get('answer')" [disabled]="formGroup.disabled"></nouislider>
```
with
```typescript
this.formGroup = new FormGroup({
    answer: new FormControl(initialValue, Validators.required)
}));
```

Later on I am disabling my formGroup using `this.formGroup.disable()` and then I get:

> It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true
> when you set up this control in your component class, the disabled attribute will actually be set in the DOM for
> you. We recommend using this approach to avoid 'changed after checked' errors.
> 
> Example: 
> form = new FormGroup({
>    first: new FormControl({value: 'Nancy', disabled: true}, Validators.required),
>    last: new FormControl('Drew', Validators.required)
> });

So, can I fix this somehow?

**Comment by dhardtke** [comment]
Okay, seems to be fixed with Angular 4. At least it is no longer happening for me.

**Comment by hardfi** [comment]
I had similar problem and it can be fixed by disabling the formGroupName from ts file itself: 

`this.formGroup.get('answer').disable()`
