### ISSUE TITLE
Update in susbcription

### ISSUE THREAD

**Issue by utiq** [tb/ng2-nouislider#77]
Hi, I would like to use the slider as a control for my HTML5 video, but it's not updating when I add it to a subscription. My code is something like this:

<nouislider [min]="0" [max]="100" [step]="1" [(ngModel)]="someValue" (change)="onChangeValue($event)" [disabled]="disabled"></nouislider>

...

```
subscription: Subscription;

constructor(private timelineService: TimelineService)  #{
    this.subscription = this.timelineService.getPosition().subscribe(position => {
        this.someValue = position;
    });

}
```

**Comment by sean-perkins** [comment]
@utiq You will have to use a `ViewChild` reference to access the wrapped component.

```
<nouislider #nouislider></nouislider>
```

You will then have to update the value directly from the upstream library... something is broken in this wrapper's implementation.

```
@ViewChild('nouislider') nouislider: any;
...
this.nouislider.slider.set(this.someValue);
```
