### ISSUE TITLE
Error while loading

### ISSUE THREAD

**Issue by mohanskumar** [tb/ng2-nouislider#78]
installed in an angular 4 cli project, getting the following error

ZoneAwareError {__zone_symbol__error: Error: Uncaught (in promise): Error: noUiSlider (9.2.0): 'start' is required.
Error: noUiSlider 

not sure anything i am missing.. any thoughts?

**Comment by tb** [comment]
@mohanskumar see https://github.com/tb/ng2-nouislider/search?q=Error%3A+noUiSlider+%289.2.0%29%3A+%27start%27+&type=Issues&utf8=%E2%9C%93
