### ISSUE TITLE
Issue:  How to show tooltips only when dragging the selector?

### ISSUE THREAD

**Issue by daBishMan** [tb/ng2-nouislider#79]
The following issue https://github.com/tb/ng2-nouislider/issues/13 is closed, but there is no solution to how to show the tooltips only when dragging the selectors not all the time.  Is this possible?

**Comment by AliObaji** [comment]
Here's how I did it using scss.
                  .noUi-tooltip {
                    display: none;
                  }


                .noUi-handle {
                  border-radius: 50% !important;
                  width: 1.5em;
                  height: 1.5em;
                  border: 2px solid #209e91;
                  &:focus {
                    outline: none;

                    .noUi-tooltip {
                      bottom: -190%;
                      font-size: 0.8em;
                      display: block;
                    }
                  }
