### ISSUE TITLE
Error When using

### ISSUE THREAD

**Issue by docaohuynh** [tb/ng2-nouislider#83]
I have error when using

```
Error: Template parse errors:
Can't bind to 'min' since it isn't a known property of 'nouislider'. ("meValue | json }}, someMin: {{ someMin | json }}, someMax: {{ someMax | json }}</code>**
```
Any help. Thanks!

**Comment by bobbybobby** [comment]
Most likely, you didn't import the module correctly thus angular doesn't have the definition of the nouislider component and its available inputs.

Make sure to import `NouisliderModule` in the `@NgModule` directive in which the component that use the slider is declared (that is not necessarily `app.module.ts`, but a submodule if you used them in your project architecture).
