### ISSUE TITLE
Error when bundling with RollupJS

### ISSUE THREAD

**Issue by noemi-salaun** [tb/ng2-nouislider#89]
Because of the name of the file **src/nouislider.js**, [RollupJS](https://github.com/rollup/rollup) mistaken `import * as noUiSlider from 'nouislider';` for itself.

<details>
  <summary>Stack trace</summary>

    Error: A module cannot import itself
    node_modules/ng2-nouislider/src/nouislider.js (2:0)
    1: import * as commonjsHelpers from ' commonjsHelpers';
    2: import 'nouislider';
       ^
    3: import '@angular/core';
    4: import '@angular/forms';

</details>

<hr/>
Just renaming the files and changing the `main` and the `typings` entry in the **package.json** do the job.

- nouisilder.d.ts -> ng2-nouislider.d.ts
- nouisilder.js -> ng2-nouislider.js
- nouisilder.metadata.json -> ng2-nouislider.metadata.json 

Do you think it would be possible to name your dist files after the name of your lib?

**Comment by nowhen** [comment]
Same problem and same workaround here.

**Comment by mkp05** [comment]
> Do you think it would be possible to name your dist files after the name of your lib?

Definitely agree. On some very common angular-starters projects this collision probably makes the library unusable (it overrides original component with the same name)...
