### ISSUE TITLE
How to reset nouislider

### ISSUE THREAD

**Issue by kamleshpaliwal-tudip** [tb/ng2-nouislider#93]
I have ng2 -nouislider in my project  for filtering. The scenerio is that after applying all filters i want to clear all filters and reset to their initial position on one button click of reset filter. i am trying this  but not able to do it.somehow i have managed to do it by reinitializing value of some rang property but it is throwing on change event.?

**Comment by kamleshpaliwal-tudip** [comment]
Sry forgot to mention, any help is apreceiated??

**Comment by Dok11** [comment]
@kamleshpaliwal-tudip my temporary decision is timeout:
```html
<nouislider ... [(ngModel)]="priceRangeCurrent" ...></nouislider>
```

```ts
onRouteChange(): {
  setTimeout(() => {
    this.priceRangeCurrent = [priceMin, priceMax];
  }, 100);
}
```

this method far far from best pratice, but I did'n find suitable public method for this or correct processing in `ngOnChanges()` in nouislider component.

**Comment by cindyssun5** [comment]
@Dok11 
Just curious as to what method you ended up using for your filtering. I am basically doing the exact same thing as you (a reset button to clear filters) and I can't figure out how to reset the slider.

@kamleshpaliwal-tudip
I tried this and it doesn't work for me. Do we have to put it on a onRouteChange or could it be on any function?
