### ISSUE TITLE
How to recreate the slider?

### ISSUE THREAD

**Issue by drunkendaddy** [tb/ng2-nouislider#96]
I need to change the number of handles on a slider. When googling it says I need to destroy and create the slider again.

I was able to destroy the slider:

```
@ViewChild('slider') slider;

destroySlider() {
    this.slider.slider.destroy();
}

```
but I can't seem to find how to create the slider. Any help is appreciated.

**Comment by kiqq** [comment]
Works for me in angular 4.3.4:
`<nouislider *ngIf="sliderReady" [(ngModel)]="sliderModel"></nouislider>`

```
sliderReady: boolean;
sliderModel: number | number[];

 constructor(private cd: ChangeDetectorRef) {}

setValue(value: number | number[]) {
    this.sliderReady = false;
    this.cd.detectChanges();
    this.sliderModel = value;
    this.sliderReady = true;
  }
```
